### ISSUE TITLE
SVMhmm is missing OSx binary

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#239]
Originally reported on Google Code with ID 239

```
The model dependency which holds the binaries needed for dkpro-tc-ml-svmhmm lacks a
version for OSx.
```

Reported by `daxenberger.j` on 2015-04-07 13:50:38

**Comment by zesch** [comment]
I have compiled the binary. Where should be store the files so that they can be installed with the script?

**Comment by reckart** [comment]
How about bintray? https://bintray.com

**Comment by reckart** [comment]
Btw. I'm planning to put stuff that was previously on google code downloads there too.

**Comment by reckart** [comment]
There already is a "DKPro Core" org on bintray. We might consider renaming that to be in-line with the "DKPro" on Github. Then we could have multiple "repositories" within that org. I didn't check recently if they have any size limits.

**Comment by daxenberger** [comment]
Why not store it with the models for other distributions on https://zoidberg.ukp.informatik.tu-darmstadt.de?
(public-model-releases-local:de/tudarmstadt/ukp/dkpro/tc/de.tudarmstadt.ukp.dkpro.tc.svmhmm-bin/20080814.0/de.tudarmstadt.ukp.dkpro.tc.svmhmm-bin-20080814.0.jar)

**Comment by zesch** [comment]
For the final model .jar - yes sure.
I meant the compiled files that also need to be stored somewhere so that the build script can download them.
Of course we could skip that step, but it seems to be DKPro policy to do it that way.

**Comment by reckart** [comment]
I published the resources separately
- so that the Ant script can pick them up (they don't have to be in the SVN/Git repo)
- so that people can use the resources independently from DKPro

If you directly generate JAR files and do not even use an Ant script, then uploading them directly to the Maven repo should be ok.

**Comment by daxenberger** [comment]
Hm, I'm still getting java.io.FileNotFoundException: No file found at [classpath:/de/tudarmstadt/ukp/dkpro/tc/svmhmm/osx-x86_64/manifest.properties] when running de.tudarmstadt.ukp.dkpro.tc.examples.single.sequence.BrownPosSVMHMMDemoTest on OSx. Can anybody reproduce this?

**Comment by zesch** [comment]
The binary is there and this used to work.
However, I have another user report with the very same error.
It remains unclear whether this is related to this issue or a new one regarding e.g. the Java8 move.

**Comment by reckart** [comment]
To those where the binary does not work: what happens when you extract it from the JAR to disk and try to run it simply on the command line? 

Maybe the binary is no longer compatible with the latest OS X?

**Comment by zesch** [comment]
I build the binary with the latest OS X.

**Comment by reckart** [comment]
Ok, I just ran this. This is the JAR where the binaries are supposed to be: `de.tudarmstadt.ukp.dkpro.tc.svmhmm-bin-20080814.0.jar` - but that one contains only linux (32/64 bit) and windows (32 bit). 

Is there maybe a newer build.xml to build a newer JAR version that should be uploaded to UKP OSS and that should be used?

**Comment by reckart** [comment]
@zesch when you added the OS X stuff to the build.xml you did not update the version in the build.xml and possibly not upload a new version to UKP OSS. Even if you uploaded a current JAR, since the version did not change, people that already had the previous JAR cached will not get the latest JAR. 

If you make changes to a JAR and do not want to change the "date version" (`20080814`) e.g. because that is the actual date of the latest upstream sources, then you must change the number after the dot, e.g. `20080814.1`.

**Comment by zesch** [comment]
Right I forgot that.
What should be the version then 20080814.1 or 2015something?

**Comment by reckart** [comment]
You could make the decision based on the latest change to the sources / timestamp of the sources - or you could base on the latest build. If I'm using pre-built binaries from third parties, I usually use the date of the build. But if all the executables are built by the TC team, you might consider the date of the sources more convenient. If in doubt, maybe throw a coin but then remain consistent for the future ;)

**Comment by zesch** [comment]
I committed the script with updated version and uploaded the jar.
Please test.

**Comment by daxenberger** [comment]
Works now.
